### ISSUE TITLE
cargo-deny doesn't igore unpublished crate `generator` as expected

### ISSUE THREAD

**Issue by davidB** [cdevents/sdk-rust#13]
```toml
# The unpublished packages (generator) would be ignored now
# FIXME the generator is excluded explicitly (see Makefile), I don't know why this is not working
[licenses.private]
ignore = true
```

Current workaround: `generator` is explicitly excluded in Makefile's call

```Makefile
lint_cargo_deny:
	cargo deny --workspace --all-features \
		--exclude-dev \
		--exclude generator \
		check licenses advisories \
		--config=tools/cargo-deny/deny.toml
```
